name: Docker Compose CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Docker Compose
      uses: docker/setup-qemu-action@v2

    - name: Build and run containers
      uses: docker/compose-action@v2
      with:
        files: docker-compose.yml
        build: true

    - name: Run tests
      run: docker-compose run fluidra

    - name: Shut down and clean up
      run: docker-compose down
